# Generated by Django 6.0.5 on 2026-05-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('nivel_urgencia', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('fecha_alerta', models.DateTimeField(auto_now_add=True)),
                ('fecha_vista', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Alertas',
                'ordering': ['-fecha_alerta'],
            },
        ),
    ]
