# Generated by Django 6.0.5 on 2026-05-22 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paciente_original', models.IntegerField(unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('edad', models.PositiveSmallIntegerField()),
                ('sexo', models.CharField(max_length=1)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EjecucionETL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_fuente', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_segundos', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('registros_extraidos', models.IntegerField(default=0)),
                ('registros_procesados', models.IntegerField(default=0)),
                ('registros_rechazados', models.IntegerField(default=0)),
                ('duplicados_eliminados', models.IntegerField(default=0)),
                ('nulos_imputados', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('en_proceso', 'en_proceso'), ('completado', 'completado'), ('fallido', 'fallido')], default='en_proceso', max_length=20)),
                ('reporte_calidad', models.JSONField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('manual', 'manual'), ('simulacion', 'simulacion'), ('automatico', 'automatico')], default='manual', max_length=20)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etl_ejecuciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogETL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR')], max_length=10)),
                ('mensaje', models.TextField()),
                ('campo_afectado', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_original', models.TextField(blank=True, null=True)),
                ('valor_corregido', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='etl.ejecucionetl')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('clasificacion_imc', models.CharField(blank=True, max_length=20, null=True)),
                ('presion_sistolica', models.IntegerField(blank=True, null=True)),
                ('presion_diastolica', models.IntegerField(blank=True, null=True)),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, null=True)),
                ('glucosa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('colesterol', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('saturacion_oxigeno', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('antecedentes_familiares', models.BooleanField(blank=True, null=True)),
                ('fumador', models.BooleanField(blank=True, null=True)),
                ('consumo_alcohol', models.BooleanField(blank=True, null=True)),
                ('actividad_fisica', models.CharField(blank=True, max_length=20, null=True)),
                ('diagnostico_preliminar', models.CharField(blank=True, max_length=100, null=True)),
                ('riesgo_enfermedad', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_consulta', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fuente_etl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='etl.ejecucionetl')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='etl.paciente')),
            ],
        ),
    ]
