# Generated by Django 6.0.5 on 2026-05-22 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='registroclinico',
            options={'verbose_name': 'Registro Clínico', 'verbose_name_plural': 'Registros Clínicos'},
        ),
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='registroclinico',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(2.5)]),
        ),
        migrations.AlterField(
            model_name='registroclinico',
            name='frecuencia_cardiaca',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(220)]),
        ),
        migrations.AlterField(
            model_name='registroclinico',
            name='glucosa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(600)]),
        ),
        migrations.AlterField(
            model_name='registroclinico',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='registroclinico',
            name='presion_diastolica',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='registroclinico',
            name='presion_sistolica',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='registroclinico',
            name='riesgo_enfermedad',
            field=models.CharField(blank=True, choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto'), ('Crítico', 'Crítico')], max_length=10, null=True),
        ),
    ]
