# Generated by Django 6.0.5 on 2026-05-22 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('algoritmo', models.CharField(choices=[('random_forest', 'Random Forest'), ('logistic_regression', 'Logistic Regression'), ('decision_tree', 'Decision Tree')], max_length=50)),
                ('version', models.CharField(max_length=20)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision_score', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('archivo_modelo', models.CharField(blank=True, max_length=255, null=True)),
                ('feature_names', models.JSONField(blank=True, null=True)),
                ('feature_importance', models.JSONField(blank=True, null=True)),
                ('entrenado_en', models.DateTimeField(auto_now_add=True)),
                ('registros_entrenamiento', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-entrenado_en'],
            },
        ),
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riesgo_predicho', models.CharField(max_length=10)),
                ('probabilidad', models.FloatField(blank=True, null=True)),
                ('factores_clave', models.JSONField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicciones', to='ml.modeloml')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='etl.paciente')),
            ],
            options={
                'verbose_name_plural': 'Predicciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
